### ISSUE TITLE
Directly output tiles

### ISSUE THREAD

**Issue by taavi223** [Mbucari/GEHistoricalImagery#1]
Is it possible to add an option to directly output the tiles, instead of assembling them into a GeoTIFF? Thanks!

**Comment by Mbucari** [comment]
Yes, that would be no problem at all. The only issue is how to organize them so that they can be useful. Do you have a naming suggestion?

**Comment by Mbucari** [comment]
Fixed in [latest release](https://github.com/Mbucari/GEHistoricalImagery/releases/tag/v0.1.7).
