### ISSUE TITLE
How to get the capture time of a certain point on Google Earth? Thanks！

### ISSUE THREAD

**Issue by Saturn87930** [Mbucari/GEHistoricalImagery#4]
How to get the capture time of a certain point on Google Earth? Thanks！

**Comment by Saturn87930** [comment]
Is it possible to retrieve the capture time through a JavaScript script? Thank you!

**Comment by kabilsharma** [comment]
Do you want to do it frequently or if you want for few times.  the Manual way is to go to Google Earth web page historical or normal satellite view and at the very left bottom of the screen you can see the imagery taken date. 
![{C5B23280-64DB-46D4-84F0-09E6129EB31D}](https://github.com/user-attachments/assets/84937921-cd33-4375-b3c7-764864b8e5dd)

**Comment by Mbucari** [comment]
@Saturn87930 kabilsharma Is right. Use Google Earth app proper to browse for the imagery you want, then use GEHistoricalImagery to grab it.

**Comment by kabilsharma** [comment]
Many the times you will find that the imagery is available with Earth but when you test with availability command it will not show. I still didn't figure out why . first thought this of a date format issue but no idea maybe temporarily not available or no idea to be honest. So yes we can check over there but no guarantee.

**Comment by Mbucari** [comment]
@kabilsharma I think when that happens, it is because Google Earth is mixing imagery from different zoom levels. If you were zoomed all the way in, it may be showing you dated tiles for zoom level 20 as well as zoom level 19.

**Comment by kabilsharma** [comment]
hmm 🤔. Double checked.  You are absolutely right.
